---
# maintains ports, bianry or repo urls

org: encapsulate
domain_regex: ^([a-zA-Z0-9-]+\.)+[a-zA-Z]{2,}$
monitor_server_dns: monitor.encapsulate.xyz
ansible_port: 8192

architecture_map:
  x86_64: amd64
  aarch64: arm64

default_node_types:
  - validator
  - default

tmp_dir: /tmp

rust:
  root: /opt
  path: /opt/cargo

solana:
  validator:
    source_url: https://github.com/jito-foundation/jito-solana.git
    ports:
      rpc_port: 8899
      dynamic_port_range: 7000-7050
  exporter:
    source_url: https://github.com/qskyhigh/solana-monitor-public
    ports:
      metrics_port: 1234
