---
# maintains versions and can overwrite all.yml
solana:
  validator:
    version: v2.2.19-jito
    known_validators:
      - 7Np41oeYqPefeNQEHSv1UDhYrehxin3NStELsSKCT4K2
      - GdnSyH3YtwcxFvQrVVJMm1JhTS4QVX7MFsX56uJLUfiZ
      - DE1bawNcRJB9rVm3buyMVfr8mBEoyyu73NBovf2oXJsJ
      - CakcnaRDHka2gXyfbEd2d3xsvkJkqsLw2akB3zsN1D2S
    entrypoints:
      - entrypoint.mainnet-beta.solana.com:8001
      - entrypoint2.mainnet-beta.solana.com:8001
      - entrypoint3.mainnet-beta.solana.com:8001
      - entrypoint4.mainnet-beta.solana.com:8001
      - entrypoint5.mainnet-beta.solana.com:8001
    expected_genesis_hash: 5eykt4UsFv8P8NJdTREpY1vzqKqZKvdpKuc147dw2N9d
    limit_ledger_size: ''
    tip_payment_program_pubkey: T1pyyaTNZsKv2WcRAB8oVnk93mLJw2XzjtVYqCsaHqt
    tip_distribution_program_pubkey: 4R3gSG8BpU4t19KYj8CfnbtRpnT8gtk4dvTHxVRwc2r7
    merkle_root_upload_authority: GZctHpWXmsZC1YHACTGGcHhYxjdRqQvTpYkb9LMvxDib
    commission_bps: 800
    relayer_url: http://amsterdam.mainnet.relayer.jito.wtf:8100
    block_engine_url: https://mainnet.block-engine.jito.wtf
    shred_receiver_address: 74.118.140.240:1002
  exporter:
    version: main
    validator_rpc_endpoint: http://localhost:8899
    network_rpc_endpoint: https://api.mainnet-beta.solana.com
    pub_key:
    vote_pub_key:
    solana_binary_path: /opt/solana/bin/solana-cli
