---
- name: Set up Solana Exporter
  hosts: all
  become: true
  gather_facts: true
  vars:
    project: "{{ group_names[0] }}"
  vars_files:
    - group_vars/all.yml
    - group_vars/{{ env }}.yml

  tasks:
    - name: Set service_identifier
      ansible.builtin.set_fact:
        service_identifier: "{{ project }}-exporter"

    - name: Include common handlers
      ansible.builtin.include_role:
        name: common

    - name: Include exporter role
      ansible.builtin.include_role:
        name: solana_exporter
