---
# maintains mainnet inventory grouped by project names
all:
  vars:
    env: mainnet
  children:
    solana:
      hosts:
        validator.solana.mainnet.encapsulate.xyz:
          type: validator
