---
# maintains testnet inventory grouped by project names
all:
  vars:
    env: testnet
  children:
    solana:
      hosts:
        validator.solana.testnet.encapsulate.xyz:
          type: validator
