---
- name: Configure sysctl settings
  ansible.builtin.copy:
    dest: "/etc/sysctl.d/90-{{ service_identifier }}-validator.conf"
    content: |
      # Increase max UDP buffer sizes
      net.core.rmem_max = 134217728
      net.core.wmem_max = 134217728

      # Increase memory mapped files limit
      vm.max_map_count = 1000000

      # Increase number of allowed open file descriptors
      fs.nr_open = 1000000
    owner: root
    group: root
    mode: "0644"
  register: sysctl_settings

- name: Apply sysctl settings
  ansible.builtin.command: sysctl --system
  when: sysctl_settings.changed
